# ASP.NET Core

# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'


variables:
  buildConfiguration: 'Release'

steps:
- task: Npm@1
  inputs:
    command: 'install'

- task: WhiteSource Bolt@20

- script: cd ..
- script: ls -l

- task: SonarCloudPrepare@1
  inputs:
    SonarCloud: 'Leo_SonarCloudConnection'
    organization: 'psviot'
    scannerMode: 'MSBuild'
    projectKey: 'mslearn-tailspin-spacegame-web'
    projectName: 'mslearn-tailspin-spacegame-web'
- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'


- task: SonarCloudAnalyze@1
- task: SonarCloudPublish@1
  inputs:
    pollingTimeoutSec: '300'
